### PR TITLE
Require helm version 3.10 or newer

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Installing with helm v3.7.1 fails with this error message:
```
Error: INSTALLATION FAILED: template: pulsar/templates/broker-statefulset.yaml:270:52: executing
 "pulsar/templates/broker-statefulset.yaml" at <eq .Values.broker.storageOffload.driver "aws-s3">: 
error calling eq: incompatible types for comparison
```

### Modifications

- Add check that verifies that Helm version is >= 3.10 (Helm 3.10.0 was released in September 2022) 
- Add CI test that verifies that installing the chart works with Helm 3.10.0

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by frankjkelly** [comment]
Thank @lhotari LGTM

**Comment by lhotari** [comment]
Thanks for the review @frankjkelly
